# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'checkconnection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for checkconnection

  target 'checkconnectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'checkconnectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'ReachabilitySwift'

end
